### ISSUE TITLE
bundle package recursive loop when using multiple gemspecs

### ISSUE THREAD

**Issue by jsmilani** [bundler/bundler#4430]
I am attempting to run 'bundle package' during a deploy of our repo, but when we do we get a recursion loop during the cp_r ending with the error: "Errno::ENAMETOOLONG: File name too long @ rb_sysopen - /Users/me/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/localizer/vendor/cache/support_rb-4a8c0775d668/.git/objects/pack/pack-13658d6ae3c302c3932bfb35ee087a28ed30533a.idx"

I have narrowed the problem down to our second gemspec in our repo that we use for a client library. When we leave it in bundler wants to package our repo inside of itself and it falls into an recursion loop until the filename gets too long and fails. Fortunately the second second '-client' gemspec is not necessary for deployments and 'bundle package' works when I comment out that line, but I have not found any way to 'bundle package' without commenting it out.

The ideal way to solve this is to have bundler look at the path of the gem it wants to package and reject it if it is the same as the project root directory. I welcome other suggestions for temporary fixes until then.

Example Gemfile:
```
source 'https://rubygems.org'
gemspec name: 'localizer'
gemspec name: 'localizer-clients'
...
```

**Comment by RochesterinNYC** [comment]
What version of Bundler are you using? I believe this was fixed in #4161 and #4393. If you try `bundle package` with Bundler `v1.12.0.rc`, does this problem continue?

**Comment by jsmilani** [comment]
I switched to 1.12.0.rc and it still goes into the recursion loop.

```
› bundle -v
Bundler version 1.12.0.rc
```

**Comment by indirect** [comment]
@jsmilani don't use `gemspec` if the gem is in the directory. Instead, use `gem "localizer", path: "./localizer"`. Then it will not be packaged.

**Comment by indirect** [comment]
If you could provide us with a reproduction case for this problem, we would be happy to fix it, however!

**Comment by jsmilani** [comment]
@indirect Unfortunately as of 1.12.0.rc the local path still attempts to put in vendor/cache and recursion loop still happens. I will create a sample repo that can reproduce the problem.

**Comment by jsmilani** [comment]
https://github.com/jsmilani/bundler_recursion

Check that out and run "bundle package --all" with current stable bundler or 1.12.0.rc

**Comment by segiddins** [comment]
Thanks @jsmilani, I can reproduce this!
