### ISSUE TITLE
The .txt (help) files have malformed ANSI sequences.

### ISSUE THREAD

**Issue by DungeonCaster** [bundler/bundler#4801]
Typing `bundler --help` produces text flooded with characters typical of ANSI escape sequences except that there are no `0x1b5b` strings in the files when examined in a hexeditor. 

**DETAILS:**
`C:\Windows\system32>ruby -v`
`ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]`

`C:\Windows\system32>gem -v`
`2.4.5.1`

`C:\Windows\system32>bundle -v`
`Bundler version 1.12.5`

`C:\Windows\system32>bundle --help`
`Could not find command "--help".`        <--- separate issue: bundle vs bundler 

`C:\Windows\system32>bundler --help`
`BUNDLE(1)                                                            BUNDLE(1)`

`1mNAME0m`
`       1mbundle 22m- Ruby Dependency Management`

`1mSYNOPSIS0m`
`       1mbundle 22mCOMMAND [--no-color] [--verbose] [ARGS]`

`1mDESCRIPTION0m`
`       Bundler  manages  an 1mapplication's dependencies 22mthrough its entire life`
`       across many machines systematically and repeatably.`

`       See the bundler website 4mhttp://bundler.io24m for  information  on  getting`
`       started, and Gemfile(5) for more information on the 1mGemfile 22mformat.`

`1mOPTIONS0m`
`       1m--no-color0m`
`              Prints all output without color`

`       1m--verbose0m`
`              Prints out additional logging information`

`1mBUNDLE COMMANDS0m`
`       We divide 1mbundle 22msubcommands into primary commands and utilities.`

`1mPRIMARY COMMANDS0m`
`       bundle install(1) 4mbundle-install.1.html0m`
`              Install the gems specified by the 1mGemfile 22mor 1mGemfile.lock0m`

`       bundle update(1) 4mbundle-update.1.html0m`
`              Update dependencies to their latest versions`

`       bundle package(1) 4mbundle-package.1.html0m`
`              Package  the  .gem  files  required by your application into the`
`              1mvendor/cache 22mdirectory`

`       bundle exec(1) 4mbundle-exec.1.html0m`
`              Execute a script in the context of the current bundle`

`       bundle config(1) 4mbundle-config.1.html0m`
`              Specify and read configuration options for bundler`

`       1mbundle help(1)0m`
`              Displays detailed help for each subcommand`

`1mUTILITIES0m`
`       1mbundle check(1)0m`
`              Determine whether the  requirements  for  your  application  are`
`              installed and available to bundler`

`       1mbundle list(1)0m`
`              Show all of the gems in the current bundle`

`       1mbundle show(1)0m`
`              Show the source location of a particular gem in the bundle`

`       1mbundle outdated(1)0m`
`              Show all of the outdated gems in the current bundle`

`       1mbundle console(1)0m`
`              Start an IRB session in the context of the current bundle`

`       1mbundle open(1)0m`
`              Open an installed gem in the editor`

`       1mbundle lock(1)0m`
`              Generate a lockfile for your dependencies`

`       1mbundle viz(1)0m`
`              Generate a visual representation of your dependencies`

`       1mbundle init(1)0m`
`              Generate a simple 1mGemfile22m, placed in the current directory`

`       bundle gem(1) 4mbundle-gem.1.html0m`
`              Create a simple gem, suitable for development with bundler`

`       bundle platform(1) 4mbundle-platform.1.html0m`
`              Displays platform compatibility information`

`       1mbundle clean(1)0m`
`              Cleans up unused gems in your bundler directory`

`1mPLUGINS0m`
`       When  running a command that isn't listed in PRIMARY COMMANDS or UTILI-`
`       TIES, Bundler will try  to  find  an  executable  on  your  path  named`
`       1mbundler-<command>  22mand  execute it, passing down any extra arguments to`
`       it.`

`1mOBSOLETE0m`
`       These commands are obsolete and should no longer be used`

`       o   1mbundle cache(1)0m`

`                                   May 2016                          BUNDLE(1)`

`C:\Windows\system32>`

**Comment by LynnCo** [comment]
Should be fixed on master as of https://github.com/bundler/bundler/pull/4802, can re-open if that's not accurate

**Comment by segiddins** [comment]
#4802 didn't change any of the actual behavior of the help command

**Comment by b-ggs** [comment]
Working on this!

**Comment by colby-swandale** [comment]
ping @DungeonCaster is still a problem in the recent releases of Bundler?

**Comment by DHB** [comment]
Still the same:
~~~
CMD: C:\Users\Development $ ver && ruby -v && gem -v && bundle -v && git --version

Microsoft Windows [Version 10.0.15058]
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
2.5.2
Bundler version 1.14.6
git version 2.12.0.windows.1
~~~

~~~
CMD: C:\Users\Development $ bundle --help
BUNDLE(1)                                                            BUNDLE(1)

1mNAME0m
       1mbundle 22m- Ruby Dependency Management

1mSYNOPSIS0m
       1mbundle 22mCOMMAND [--no-color] [--verbose] [ARGS]

1mDESCRIPTION0m
       Bundler  manages  an 1mapplication's dependencies 22mthrough its entire life
       across many machines systematically and repeatably.

       See the bundler website 4mhttp://bundler.io24m for  information  on  getting
       started, and Gemfile(5) for more information on the 1mGemfile 22mformat.
...
~~~


git bash:

~~~ bash
Development@DHB-LAPTOP: /h/workspace5 $ bash --version | head -n 1 && ruby -v && gem -v && bundle -v && git --version
GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
2.5.2
Bundler version 1.14.6
git version 2.12.0.windows.1
~~~
~~~ bash
Development@DHB-LAPTOP: /h/workspace5 $ bundle --help
BUNDLE(1)                                                            BUNDLE(1)

1mNAME0m
       1mbundle 22m- Ruby Dependency Management

1mSYNOPSIS0m
       1mbundle 22mCOMMAND [--no-color] [--verbose] [ARGS]

1mDESCRIPTION0m
       Bundler  manages  an 1mapplication's dependencies 22mthrough its entire life
       across many machines systematically and repeatably.

       See the bundler website 4mhttp://bundler.io24m for  information  on  getting
       started, and Gemfile(5) for more information on the 1mGemfile 22mformat.
...
~~~

**Comment by unak** [comment]
Any progress?

BTW, this is not only Windows problem.
The publisher of Bundler gem can check the *.txt files in your gem files.
These broken files are built by you and distributed via RubyGems.org.

**Comment by segiddins** [comment]
I can't reproduce this, `bundle --help` on my machine shows the bolding etc as intended.

**Comment by colby-swandale** [comment]
@segiddins This is only reproducible on Windows and some instances of Linux as well.

**Comment by indirect** [comment]
I'm not sure what a fix for this would look like... is there some way we could alter the contents of the man pages to display correctly on windows? Should we be stripping all ansi formatting before displaying on windows?

**Comment by segiddins** [comment]
Maybe we need to check `if $stdout.tty?` and strip ansi codes otherwise?

**Comment by colby-swandale** [comment]
@segiddins i can get this problem on linux inside a regular bash session. 

I can take a quick look at this and see what i can find out seeing i can reproduce this issue.
