### ISSUE TITLE
Bundler won't install any new gems in the Gemfile

### ISSUE THREAD

**Issue by manikjain** [bundler/bundler#6901]
I'm working on an existing project and trying to install new gems by adding an entry into the Gemfile. However, I keep getting a cyclic dependency error for just about any ruby gem that I try to install.

Here's how the original Gemfile looks:
```
$ cat Gemfile
source 'https://rubygems.org'
group :development do
  gem 'pry'
  gem 'rspec'
  gem 'rubocop'
  gem 'simplecov'
  gem 'webmock'
end

ENV['OVERRIDE_CUSTOM1_GEM_VERSION'] = '1.2'
gem 'custom1', git: 'git@github.com:name/custom1'

gemspec
```

I ran a `bundle install` (which succeeded) and then modified it to the following:
```
$ cat Gemfile
source 'https://rubygems.org'
group :development do
  gem 'pry'
  gem 'rspec'
  gem 'rubocop'
  gem 'simplecov'
  gem 'webmock'
end

ENV['OVERRIDE_CUSTOM1_GEM_VERSION'] = '1.2'
gem 'custom1', git: 'git@github.com:name/custom1'
gem 'custom2', git: 'git@github.com:name/custom2'

gemspec
```

Ran another `bundle install` and got the following message:
```
$ bundle install
Fetching git@github.com:name/custom2
Warning: Permanently added ***** to the list of known hosts.
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Your bundle requires gems that depend on each other, creating an infinite loop. Please remove gem 'rubygems' and try again.
```

When I try to install another gem by the name `gem 'jira-ruby', '~> 1.1'`, I get:
```
$ bundle install
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Your bundle requires gems that depend on each other, creating an infinite loop. Please remove gem 'rubygems' and try again.
$
```

I tried erasing all data from Gemfile.lock and then running `bundle update` which didn't work. The existing project repo also consists of a `./vendor/cache` directory which contains all the installed gems. I already tried removing the gems from vendor/cache and reinstalling, that didn't work too.

Please suggest how this issue could be resolved.

**Comment by greysteil** [comment]
Can you tell us your Bundler and Rubygems versions? You can get both with the command `bundle env`.

**Comment by manikjain** [comment]
Thanks @greysteil for the quick response. Here are the details as requested:

Note:- I've cleaned up some names. `project-repo` below refers to the git project I'm working in and trying to install gems into.

## Environment
```
Bundler   1.14.6
Rubygems  2.4.8.1.org
Ruby      2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]
Git       2.7.4
Platform  x86_64-linux
```
### Gemfile.lock
```
GIT
  remote: git@github.com:name/custom1
  revision: *************
  specs:
    custom1 (1.2)
      activesupport (= 4.2.6)
      aws-sdk (= 2.3.19)
      aws-sdk-v1 (= 1.63.0)
      builder (= 3.0.0)
      colorize (= 0.8.1)
      excon (= 0.49.0)
      fog-core (= 1.32.1)
      fog-dynect (= 0.0.1)
      fog-json (= 1.0.2)
      fog-xml (= 0.1.2)
      git (= 1.3.0)
      gzip (= 1.0)
      highline (= 1.6.9)
      httpclient (= 2.2.4)
      ipaddress (= 0.8.0)
      json (= 1.8.3)
      json_pure (= 1.8.3)
      mime-types (= 2.4.3)
      multi_json (= 1.10.0)
      multi_xml (= 0.5.3)
      mysql (= 2.9.1)
      mysql2 (= 0.3.17)
      net-netrc (= 0.2.2)
      net-ping (= 2.0.1)
      net-scp (= 1.1.2)
      net-ssh (= 3.0.2)
      net-ssh-gateway (= 1.1.0)
      nokogiri (= 1.6.8)
      oj (= 2.9.0)
      open4 (= 1.3.0)
      ox (= 2.4.5)
      popen4 (= 0.1.2)
      ruby-duration (= 3.2.3)
      statsd-ruby (= 1.1.0)
      terminal-table (= 1.4.5)
      thor (= 0.19.1)
      thrift (= 0.9.3.0)
      uuidtools (= 2.1.4)

PATH
  remote: .
  specs:
    project-repo (0.0.1)
      custom1
      hashie (< 3.5)
      highline
      json
      oauth
      typhoeus
      zendesk_api (= 1.14.0)

GEM
  remote: https://rubygems.org/
  specs:
    Platform (0.4.0)
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.5.0)
      public_suffix (~> 2.0, >= 2.0.2)
    ast (2.3.0)
    aws-sdk (2.3.19)
      aws-sdk-resources (= 2.3.19)
    aws-sdk-core (2.3.19)
      jmespath (~> 1.0)
    aws-sdk-resources (2.3.19)
      aws-sdk-core (= 2.3.19)
    aws-sdk-v1 (1.63.0)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
    builder (3.0.0)
    coderay (1.1.1)
    colorize (0.8.1)
    crack (0.4.3)
      safe_yaml (~> 1.0.0)
    diff-lcs (1.3)
    docile (1.1.5)
    ethon (0.10.1)
      ffi (>= 1.3.0)
    excon (0.49.0)
    faraday (0.11.0)
      multipart-post (>= 1.2, < 3)
    ffi (1.9.17)
    fog-core (1.32.1)
      builder
      excon (~> 0.45)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-dynect (0.0.1)
      fog-core
      fog-json
      fog-xml
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    formatador (0.2.5)
    git (1.3.0)
    gzip (1.0)
    hashdiff (0.3.2)
    hashie (3.4.6)
    highline (1.6.9)
    httpclient (2.2.4)
    i18n (0.8.1)
    inflection (1.0.0)
    ipaddress (0.8.0)
    iso8601 (0.9.1)
    jmespath (1.3.1)
    json (1.8.3)
    json_pure (1.8.3)
    method_source (0.8.2)
    mime-types (2.4.3)
    mini_portile2 (2.1.0)
    minitest (5.10.1)
    multi_json (1.10.0)
    multi_xml (0.5.3)
    multipart-post (2.0.0)
    mysql (2.9.1)
    mysql2 (0.3.17)
    net-netrc (0.2.2)
      Platform (>= 0.3.0)
    net-ping (2.0.1)
    net-scp (1.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (3.0.2)
    net-ssh-gateway (1.1.0)
      net-ssh (>= 1.99.1)
    nokogiri (1.6.8)
      mini_portile2 (~> 2.1.0)
      pkg-config (~> 1.1.7)
    oauth (0.5.1)
    oj (2.9.0)
    open4 (1.3.0)
    ox (2.4.5)
    parser (2.4.0.0)
      ast (~> 2.2)
    pkg-config (1.1.7)
    popen4 (0.1.2)
      Platform (>= 0.4.0)
      open4 (>= 0.4.0)
    powerpack (0.1.1)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    public_suffix (2.0.5)
    rainbow (2.2.1)
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.4)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)
    rubocop (0.47.1)
      parser (>= 2.3.3.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    ruby-duration (3.2.3)
      activesupport (>= 3.0.0)
      i18n
      iso8601
    ruby-progressbar (1.8.1)
    safe_yaml (1.0.4)
    scrub_rb (1.0.1)
    simplecov (0.13.0)
      docile (~> 1.1.0)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.0)
    slop (3.6.0)
    statsd-ruby (1.1.0)
    terminal-table (1.4.5)
    thor (0.19.1)
    thread_safe (0.3.6)
    thrift (0.9.3.0)
    typhoeus (1.1.2)
      ethon (>= 0.9.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    unicode-display_width (1.1.3)
    uuidtools (2.1.4)
    webmock (2.3.2)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
    zendesk_api (1.14.0)
      faraday (~> 0.9)
      hashie (>= 1.2, < 4.0, != 3.3.0)
      inflection
      mime-types
      multipart-post (~> 2.0)
      scrub_rb (~> 1.0.1)

PLATFORMS
  ruby

DEPENDENCIES
  custom1!
  project-repo!
  pry
  rspec
  rubocop
  simplecov
  webmock

BUNDLED WITH
   1.10.6
```

**Comment by greysteil** [comment]
Ah great - can you try `gem update bundler -v1.7.3`? That should fix this for you (I think - we improved the way circular dependencies are handled).

**Comment by greysteil** [comment]
Ha! Oops, yes, I mean 1.17.3

**Comment by colby-swandale** [comment]
ping @manikjain

**Comment by manikjain** [comment]
@greysteil @colby-swandale Sorry for the delayed response. This appears to be related to the way gems were setup in one of the linked repositories further down the nested projects (as informed by my colleague), which still isn't very clear. But I think it's ok to assume for now that it may be unrelated to bundler as such. The issue can be closed.

**Comment by greysteil** [comment]
Thanks @manikjain
